default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: entertainment-api_development
  username: esteban
  password: esteban123

test:
  <<: *default
  database: entertainment-api_test

production:
  <<: *default
  database: entertainment-api_production
  username: entertainment-api
  password: <%= ENV['ENTERTAINMENT-API_DATABASE_PASSWORD'] %>
